version: "3"

services:
  app:
    image: golang:1.19
    #image: alpine
    #build: .
    ports:
      - "3003:3000"
    volumes:
      - ./:/app
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres/postgres?sslmode=disable
    working_dir: /app
    #command: go run server_postgres.go
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 750M

  postgres:
    image: postgres:alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
       - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./my-postgres.conf:/var/lib/postgresql/data/postgresql.conf
      #- ./my-postgres.conf:/etc/postresql.conf
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 750M

  tester:
    image: alpine
    ports:
      - "3333:3333"
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  postgres-data:
